version: 2
updates:
  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      typescript:
        patterns:
          - typescript
          - 'typescript-*'
        update-types:
          minor: true
          patch: true

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 2

  - package-ecosystem: npm
    directory: /server
    schedule:
      interval: weekly
    open-pull-requests-limit: 2

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5