export const FAMOUS_SWIMMER_NAMES = [
  'Michael Phelps',
  'Katie Ledecky',
  'Caeleb Dressel',
  'Ryan Lochte',
  'Missy Franklin',
  'Ian Thorpe',
  'Natalie Coughlin',
  'Sun Yang',
  'Nathan Adrian',
  'Simone Manuel',
  'Lilly King',
  'Adam Peaty',
  'Sarah Sjostrom',
  'Katinka Hosszu',
  'Florent Manaudou',
  'Joseph Schooling',
  'Ariarne Titmus',
  'Kyle Chalmers',
  'Cody Miller',
  'Jimmy Feigen',
  'Dawn Fraser',
  'Mark Spitz',
  'Matt Biondi',
  'Jenny Thompson',
  'Alexander Popov',
  'Pieter van den Hoogenband',
  'Kristin Otto',
  'Dara Torres',
  'Jason Lezak',
  'Federica Pellegrini',
];